CostControl.Presentation/Controllers/InventoryController.cs
namespace CostControl.Presentation.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using CostControl.BusinessEntity.Models.CostControl;
    using Microsoft.AspNetCore.Mvc;

    public class InventoryController : BaseController
    {
        public IActionResult InventoryList(string param)
        {
            ViewData["title"] = Helper.GetEntityTitle<Inventory>(EnumTitle.List);

            return View(Helper.GetServiceResponse<Inventory>("Get?PageNumber=1&PageSize=1000&searchKey=null&SortOrder=id&token=1"));
        }

        public IActionResult AddInventory()
        {
            ViewData["title"] = Helper.GetEntityTitle<Inventory>(EnumTitle.Add);

            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddInventory(Inventory Inventory)
        {
            if (ModelState.IsValid)
            {
                var postResult = Helper.PostValueToSevice<Inventory>("POST", Inventory);

                return Json(new { success = postResult.result, message = postResult.message });
            }

            return Json(new
            {
                model = Inventory,
                success = false,
                message = ModelState
                .Values
                .FirstOrDefault(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                .Errors
                .FirstOrDefault()
                .ErrorMessage ?? "Model Is Not Vald!"
            });
        }

        public IActionResult EditInventory(long id)
        {
            ViewData["title"] = Helper.GetEntityTitle<Inventory>(EnumTitle.Edit);

            return PartialView(GetInventoryById(id));
        }

        [HttpPost]
        public IActionResult EditInventory(long id, Inventory Inventory)
        {
            if (ModelState.IsValid)
            {
                Inventory.State = BusinessEntity.Models.Base.Enums.ObjectState.Active;

                var postResult = Helper.PostValueToSevice<Inventory>("PUT?id=" + Inventory.Id.ToString(), Inventory);

                return Json(new { success = postResult.result, message = postResult.message });
            }

            return Json(new
            {
                model = Inventory,
                success = false,
                message = ModelState
                .Values
                .FirstOrDefault(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                .Errors
                .FirstOrDefault()
                .ErrorMessage ?? "Model Is Not Vald!"
            });
        }

        public IActionResult DeleteInventory(long id)
        {
            ViewData["title"] = Helper.GetEntityTitle<Inventory>(EnumTitle.Delete);

            return PartialView(GetInventoryById(id));
        }

        [HttpPost]
        public IActionResult DeleteInventory(Inventory Inventory)
        {
            var postResult = Helper.PostValueToSevice<Inventory>("Delete?id=" + Inventory.Id.ToString(), Inventory);

            return Json(new { success = postResult.result, message = postResult.message });

        }

        private Inventory GetInventoryById(long id)
        {
            return (Helper.GetServiceResponse<Inventory>("GetById?id=" + id.ToString()).data as List<Inventory>)
                .FirstOrDefault();
        }
    }
}

CostControl.Presentation/Views/Inventory/AddInventory.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Inventory
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var error = string.Empty;
}

@using (Html.BeginForm("AddInventory", "Inventory", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-10">
				@Html.CheckBoxFor(model => model.IsWasted, new { htmlAttributes = new { @class = "form-control" } })
				@Html.LabelFor(model => model.IsWasted)
				@Html.ValidationMessageFor(model => model.IsWasted, "", new { @class = "text-danger" })
			</div>
		</div>

		<div id="errorContent" class="text-danger">

		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-success" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function displayErrorMessage(error) {
			$("#errorContent").html(error);
		}

		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('#apModal').modal('hide');
						getData('InventoryList', 'Inventory');
					} else {
						displayErrorMessage(data.message);
						return false;
					}
				}
			});

			return false;
		}
	</script>
}

CostControl.Presentation/Views/Inventory/DeleteInventory.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Inventory
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DeleteInventory", "Inventory", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div>
		<div>
			<h3> "@Model.Name" <br /> آیا اطمینان در حذف دارید؟</h3>
		</div>

		<br />

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="حذف" class="btn btn-danger" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('body').removeClass('modal-open');
						$('.modal-backdrop').remove();
						$('#apModal').hide();
						getData('InventoryList', 'Inventory');
					} else {
						return false;
					}
				}
			});

			return false;
		}
	</script>
}

CostControl.Presentation/Views/Inventory/EditInventory.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Inventory
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var error = string.Empty;
}

@using (Html.BeginForm("EditInventory", "Inventory", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div class="form-group">
			@Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-10">
				@Html.CheckBoxFor(model => model.IsWasted, new { htmlAttributes = new { @class = "form-control" } })
				@Html.LabelFor(model => model.IsWasted)
				@Html.ValidationMessageFor(model => model.IsWasted, "", new { @class = "text-danger" })
			</div>
		</div>

		<div id="errorContent" class="text-danger">

		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-success" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function displayErrorMessage(error) {
			$("#errorContent").html(error);
		}

		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('body').removeClass('modal-open');
						$('.modal-backdrop').remove();
						$('#apModal').hide();

						getData('InventoryList', 'Inventory');
					} else {
						displayErrorMessage(data.message);
						return false;
					}
				}
			});
			return false;
		}
	</script>
}

CostControl.Presentation/Views/Inventory/InventoryList.cshtml
@model CostControl.API.Models.ServiceResponse<CostControl.BusinessEntity.Models.CostControl.Inventory>

@{
	Layout = null;
	var addTitle = Helper.GetEntityTitle<CostControl.BusinessEntity.Models.CostControl.Inventory>(EnumTitle.Add);
	var editTitle = Helper.GetEntityTitle<CostControl.BusinessEntity.Models.CostControl.Inventory>(EnumTitle.Edit);
	var deleteTitle = Helper.GetEntityTitle<CostControl.BusinessEntity.Models.CostControl.Inventory>(EnumTitle.Delete);
}

<div class="row well">
	<div class="col-md-6">
		<div class="btn-group" data-toggle="modal">
			<a id="btnAddInventory" href="#" class="btn btn-primary"
			   onclick='createEntityModal("Inventory/AddInventory", "@addTitle")'>
				<span class="fa fa-plus"> <i> جدید</i></span>
			</a>
		</div>
	</div>
</div>

<table id="Inventoryslist" class="table table-bordered table-striped table-hover">
	<thead>
		<tr>
			<th>شناسه</th>
			<th>نام</th>
			<th>کد</th>
			<th>ضایعات</th>
			<th></th>
		</tr>
	</thead>
	<tbody id="setInventoryList">
		@foreach (var item in Model.data)
		{
			<tr id="tr_@item.Id">
				<td>@item.Id</td>
				<td id="td_Name">@item.Name</td>
				<td id="td_Code">@item.Code</td>
				<td id="td_IsWasted">
					<input checked="@item.IsWasted" id="IsWasted"
						   name="IsHall" type="checkbox"
						   value="@item.IsWasted" disabled />
				</td>
				<td>
					<a href="#" class="btn btn-sm btn-warning"
					   onclick="EditEntityModal(@item.Id, 'Inventory/EditInventory/', '@editTitle')">
						<i class="fa fa-edit"><span> ویرایش </span></i>
					</a>

					<span> | </span>
					<a class="btn btn-sm btn-danger"
					   onclick="DeleteEntityModal(@item.Id, 'Inventory/DeleteInventory/', '@deleteTitle', '@item.Name')">
						<i class="fa fa-trash"><span> حذف </span></i>
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<script>
	$(document).ready(function () {
		$('#pageTitle').html('@ViewData["title"]');
		$('#Inventoryslist').dataTable({
			"language": {
				"url": "/lib/DataTables/i18n/Persian.lang.json"
			}
		});
	});
</script>