CostControl.Presentation/Controllers/DraftController.cs
namespace CostControl.Presentation.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using CostControl.BusinessEntity.Models.CostControl;
    using Microsoft.AspNetCore.Mvc;

    public class DraftController : BaseController
    {
        public IActionResult DraftList(string param)
        {
            ViewData["title"] = Helper.GetEntityTitle<Draft>(EnumTitle.List);

            return View(Helper.GetServiceResponse<Draft>("Get?PageNumber=1&PageSize=1000&searchKey=null&SortOrder=id&token=1"));
        }

        public IActionResult AddDraft()
        {
            ViewData["title"] = Helper.GetEntityTitle<Draft>(EnumTitle.Add);

            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddDraft(Draft Draft)
        {
            if (ModelState.IsValid)
            {
                var postResult = Helper.PostValueToSevice<Draft>("POST", Draft);

                return Json(new { success = postResult.result, message = postResult.message });
            }

            return Json(new
            {
                model = Draft,
                success = false,
                message = ModelState
                .Values
                .FirstOrDefault(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                .Errors
                .FirstOrDefault()
                .ErrorMessage ?? "Model Is Not Vald!"
            });
        }

        public IActionResult EditDraft(long id)
        {
            ViewData["title"] = Helper.GetEntityTitle<Draft>(EnumTitle.Edit);

            return PartialView(GetDraftById(id));
        }

        [HttpPost]
        public IActionResult EditDraft(long id, Draft Draft)
        {
            if (ModelState.IsValid)
            {
                Draft.State = BusinessEntity.Models.Base.Enums.ObjectState.Active;

                var postResult = Helper.PostValueToSevice<Draft>("PUT?id=" + Draft.Id.ToString(), Draft);

                return Json(new { success = postResult.result, message = postResult.message });
            }

            return Json(new
            {
                model = Draft,
                success = false,
                message = ModelState
                .Values
                .FirstOrDefault(e => e.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                .Errors
                .FirstOrDefault()
                .ErrorMessage ?? "Model Is Not Vald!"
            });
        }

        public IActionResult DeleteDraft(long id)
        {
            ViewData["title"] = Helper.GetEntityTitle<Draft>(EnumTitle.Delete);

            return PartialView(GetDraftById(id));
        }

        [HttpPost]
        public IActionResult DeleteDraft(Draft Draft)
        {
            var postResult = Helper.PostValueToSevice<Draft>("Delete?id=" + Draft.Id.ToString(), Draft);

            return Json(new { success = postResult.result, message = postResult.message });
        }

        private Draft GetDraftById(long id)
        {
            return (Helper.GetServiceResponse<Draft>("GetById?id=" + id.ToString()).data as List<Draft>)
                .FirstOrDefault();
        }
    }
}

CostControl.Presentation/Views/Draft/AddDraft.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Draft
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var error = string.Empty;
}

@using (Html.BeginForm("AddDraft", "Draft", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div class="form-group">
			@Html.LabelFor(model => model.SaleCostPointId, htmlAttributes: new { @class = "control-label col-md-5" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.SaleCostPointId, ViewBag.SaleCostPoint as IEnumerable<SelectListItem>,
						"انتخاب کنید ...", htmlAttributes: new { @class = "selectpicker form-control" })
				@Html.ValidationMessageFor(model => model.SaleCostPointId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.SaleCostPointId, htmlAttributes: new { @class = "control-label col-md-5" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.SaleCostPointId, ViewBag.SaleCostPoint as IEnumerable<SelectListItem>,
						"انتخاب کنید ...", htmlAttributes: new { @class = "selectpicker form-control" })
				@Html.ValidationMessageFor(model => model.SaleCostPointId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.SaleCostPointId, htmlAttributes: new { @class = "control-label col-md-5" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.SaleCostPointId, ViewBag.SaleCostPoint as IEnumerable<SelectListItem>,
						"انتخاب کنید ...", htmlAttributes: new { @class = "selectpicker form-control" })
				@Html.ValidationMessageFor(model => model.SaleCostPointId, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DraftDate, htmlAttributes: new { @class = "control-label col-md-3" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.DraftDate, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.DraftDate, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
			</div>
		</div>

		<div id="errorContent" class="text-danger">

		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-success" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		$(document).ready(function () {
			$(".selectpicker").chosen({ /*rtl: true,*/ width: "100%" });
		});

		function displayErrorMessage(error) {
			$("#errorContent").html(error);
		}

		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('#apModal').modal('hide');
						getData('DraftList', 'Draft');
					} else {
						displayErrorMessage(data.message);
						return false;
					}
				}
			});

			return false;
		}
	</script>
}

CostControl.Presentation/Views/Draft/DeleteDraft.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Draft
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DeleteDraft", "Draft", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div>
		<div>
			<h3>آیا اطمینان در حذف دارید؟</h3>
		</div>

		<br />

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="حذف" class="btn btn-danger" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('body').removeClass('modal-open');
						$('.modal-backdrop').remove();
						$('#apModal').hide();
						getData('DraftList', 'Draft');
					} else {
						return false;
					}
				}
			});

			return false;
		}
	</script>
}

CostControl.Presentation/Views/Draft/DraftList.cshtml
@model CostControl.API.Models.ServiceResponse<CostControl.BusinessEntity.Models.CostControl.Draft>

@{
	Layout = null;
	var addTitle = Helper.GetEntityTitle<CostControl.BusinessEntity.Models.CostControl.Draft>(EnumTitle.Add);
	var editTitle = Helper.GetEntityTitle<CostControl.BusinessEntity.Models.CostControl.Draft>(EnumTitle.Edit);
	var deleteTitle = Helper.GetEntityTitle<CostControl.BusinessEntity.Models.CostControl.Draft>(EnumTitle.Delete);
}

<div class="row well">
	<div class="col-md-6">
		<div class="btn-group" data-toggle="modal">
			<a id="btnAddDraft" href="#" class="btn btn-primary"
			   onclick='createEntityModal("Draft/AddDraft", "@addTitle")'>
				<span class="fa fa-plus"> <i> حواله انبار جدید</i></span>
			</a>

			<a id="btnAddDepo" href="#" class="btn btn-primary"
			   onclick='createEntityModal("Draft/AddDraft", "@addTitle")'>
				<span class="fa fa-plus"> <i> حواله آشپزخانه جدید</i></span>
			</a>

		</div>
	</div>
</div>

<table id="Draftslist" class="table table-bordered table-striped table-hover">
	<thead>
		<tr>
			<th>شناسه</th>
			<th>نام</th>
			<th>کد</th>
			<th></th>
		</tr>
	</thead>
	<tbody id="setDraftList">
		@foreach (var item in Model.data)
		{
			<tr id="tr_@item.Id">
				<td>@item.Id</td>
				<td id="td_Name">@item.Id</td>
				<td id="td_Code">@item.Id</td>
				<td>
					<a href="#" class="btn btn-sm btn-warning"
					   onclick="EditEntityModal(@item.Id, 'Draft/EditDraft/', '@editTitle (@item.Id)')">
						<i class="fa fa-edit"><span> ویرایش </span></i>
					</a>

					<span> | </span>
					<a class="btn btn-sm btn-danger"
					   onclick="DeleteEntityModal(@item.Id, 'Draft/DeleteDraft/', '@deleteTitle', '@item.Id')">
						<i class="fa fa-trash"><span> حذف </span></i>
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<script>
	$(document).ready(function () {
		$('#pageTitle').html('@ViewData["title"]');
		$('#Draftslist').dataTable({
			"language": {
				"url": "/lib/DataTables/i18n/Persian.lang.json"
			}
		});
	});
</script>

CostControl.Presentation/Views/Draft/EditDraft.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Draft
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var error = string.Empty;
}

@using (Html.BeginForm("EditDraft", "Draft", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div id="errorContent" class="text-danger">

		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-success" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function displayErrorMessage(error) {
			$("#errorContent").html(error);
		}

		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('body').removeClass('modal-open');
						$('.modal-backdrop').remove();
						$('#apModal').hide();

						getData('DraftList', 'Draft');
					} else {
						displayErrorMessage(data.message);
						return false;
					}
				}
			});
			return false;
		}
	</script>
}