CostControl.Presentation/Controllers/BuffetController.cs
namespace CostControl.Presentation.Controllers
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Net.Http;
	using System.Net.Http.Headers;
	using CostControl.API.Models;
	using CostControl.BusinessEntity.Models.CostControl;
	using Microsoft.AspNetCore.Mvc;

	public class BuffetController : BaseController
	{
		public IActionResult BuffetList(string param)
		{
			ViewData["title"] = "Buffet List";

			ServiceResponse<Buffet> values = null;

			string str = string.Empty;
			using (var client = new HttpClient())
			{
				client.BaseAddress = new Uri("http://localhost:5001/api/Buffet/");

				client.DefaultRequestHeaders.Clear();
				client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));

				client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

				//HTTP GET
				var responseTask = client.GetAsync("Get?PageNumber=1&PageSize=1000&searchKey=null&SortOrder=id&token=1");
				responseTask.Wait();

				var result = responseTask.Result;
				if (result.IsSuccessStatusCode)
				{
					var readTask = result.Content.ReadAsAsync<ServiceResponse<Buffet>>();

					readTask.Wait();

					values = readTask.Result;
				}
				else //web api sent error response 
				{
					//log response status here..

					values = null;

					ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");

					str = "Server error. Please contact administrator.";
				}
			}

			//return PartialView("~/Views/Buffet/BuffetList.cshtml");
			return View(values);
		}

		public IActionResult AddBuffet()
		{
			return PartialView();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult AddBuffet(Buffet Buffet)
		{
			//https://johnthiriet.com/efficient-post-calls/
			if (ModelState.IsValid)
			{
				using (var client = new HttpClient())
				{
					client.BaseAddress = new Uri("http://localhost:5001/api/Buffet/");

					var result = client.PostAsJsonAsync("POST", Buffet);
					result.Wait();
					var res = result.Result;

					if (res.IsSuccessStatusCode)
					{
						var p1 = res.Content.ReadAsStringAsync();
						var p = res.Content.ReadAsStringAsync().Result;
					}
				}
			}
			return Json(new { success = true, message = "Ok" });
		}

		public IActionResult EditBuffet(long id)
		{
			return PartialView(GetBuffetById(id));
		}

		[HttpPost]
		public IActionResult EditBuffet(long id, Buffet Buffet)
		{
			try
			{
				if (ModelState.IsValid)
				{
					Buffet.State = BusinessEntity.Models.Base.Enums.ObjectState.Active;

					using (var client = new HttpClient())
					{
						client.BaseAddress = new Uri("http://localhost:5001/api/Buffet/");

						var result = client.PostAsJsonAsync("PUT?id=" + id.ToString(), Buffet);
						result.Wait();
						var res = result.Result;

						if (res.IsSuccessStatusCode)
						{
							var p1 = res.Content.ReadAsStringAsync();
							var p = res.Content.ReadAsStringAsync().Result;
						}
					}
				}
				return Json(new { success = true, message = "Ok" });
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
		}

		public IActionResult DeleteBuffet(long id)
		{
			return PartialView(GetBuffetById(id));
		}

		[HttpPost]
		public IActionResult DeleteBuffet(Buffet Buffet)
		{
			try
			{
				using (var client = new HttpClient())
				{
					client.BaseAddress = new Uri("http://localhost:5001/api/Buffet/");

					var result = client.PostAsJsonAsync("Delete?id=" + Buffet.Id.ToString(), Buffet);
					result.Wait();
					var res = result.Result;

					if (res.IsSuccessStatusCode)
					{
						var p1 = res.Content.ReadAsStringAsync();
						var p = res.Content.ReadAsStringAsync().Result;
					}
				}
				return Json(new { success = true, message = "Ok" });
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
		}

		private Buffet GetBuffetById(long id)
		{
			ServiceResponse<Buffet> value = null;
			string str = string.Empty;
			using (var client = new HttpClient())
			{
				client.BaseAddress = new Uri("http://localhost:5001/api/Buffet/");

				client.DefaultRequestHeaders.Clear();
				client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));

				client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

				//HTTP GET
				var responseTask = client.GetAsync("GetById?id=" + id.ToString());
				responseTask.Wait();

				var result = responseTask.Result;
				if (result.IsSuccessStatusCode)
				{
					var readTask = result.Content.ReadAsAsync<ServiceResponse<Buffet>>();

					readTask.Wait();

					value = readTask.Result;

					return (value.data as List<Buffet>).FirstOrDefault();
				}
				else //web api sent error response 
				{
					//log response status here..

					value = null;

					ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");

					str = "Server error. Please contact administrator.";
				}

				return null;
			}
		}

		public IActionResult PostBuffet(string name)
		{
			return null;
		}
	}
}

CostControl.Presentation/Views/Buffet/AddBuffet.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Buffet
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var error = string.Empty;
}

@using (Html.BeginForm("AddBuffet", "Buffet", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div id="errorContent" class="text-danger">

		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-success" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function displayErrorMessage(error) {
			$("#errorContent").html(error);
		}

		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('#apModal').modal('hide');
						getData('BuffetList', 'Buffet');
					} else {
						displayErrorMessage(data.message);
						return false;
					}
				}
			});

			return false;
		}
	</script>
}

CostControl.Presentation/Views/Buffet/BuffetList.cshtml
@model CostControl.API.Models.ServiceResponse<CostControl.BusinessEntity.Models.CostControl.Buffet>

@{
	ViewData["Title"] = "فهرست مرکز فروش ها";
	Layout = null;
}

<div class="row well">
	@*<fieldset>
		<legend></legend>*@
	<div class="col-md-6">
		<div class="btn-group" data-toggle="modal">
			<a id="btnAddBuffet" href="#" class="btn btn-primary" onclick='createEntityModal("Buffet/AddBuffet", "مرکز هزینه")'>
				<i class="fa fa-plus"> جدید </i>
			</a>

		</div>
	</div>
</div>

<br />

<table id="Buffetslist" class="table table-bordered table-striped table-hover">
	<thead>
		<tr>
			<th>شناسه</th>
			<th>نام</th>
			<th>کد</th>
			<th></th>
		</tr>
	</thead>
	<tbody id="setBuffetList">
		@foreach (CostControl.BusinessEntity.Models.CostControl.Buffet item in Model.data)
		{
			<tr id="tr_@item.Id">
				<td>@item.Id</td>
				<td id="td_Name">@item.Id</td>
				<td id="td_Code">@item.Id</td>
				<td>
					<a href="#" class="btn btn-sm btn-warning" onclick="edit(@item.Id)"> <i class="fa fa-edit"> ویرایش </i> </a>
					<span> | </span>
					<a class="btn btn-sm btn-danger" onclick="mydelete(@item.Id)"> <i class="fa fa-trash"> حذف </i> </a>

				</td>
			</tr>
		}
	</tbody>
</table>

<script>
	$(document).ready(function () {
		$('#pageTitle').html('@ViewData["title"]');
		$('#Buffetslist').dataTable({
			"language": {
				"url": "/lib/DataTables/i18n/Persian.lang.json"
			}
		});
	});
</script>

CostControl.Presentation/Views/Buffet/DeleteBuffet.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Buffet
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DeleteBuffet", "Buffet", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div>
		<div>
			<h3>آیا اطمینان در حذف دارید؟</h3>
		</div>

		<br />

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="حذف" class="btn btn-danger" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('body').removeClass('modal-open');
						$('.modal-backdrop').remove();
						$('#apModal').hide();
						getData('BuffetList', 'Buffet');
					} else {
						return false;
					}
				}
			});

			return false;
		}
	</script>
}

CostControl.Presentation/Views/Buffet/EditBuffet.cshtml
@model CostControl.BusinessEntity.Models.CostControl.Buffet
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var error = string.Empty;
}

@using (Html.BeginForm("EditBuffet", "Buffet", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div id="errorContent" class="text-danger">

		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="ثبت" class="btn btn-success" />
				<input id="btnCancel" type="button" class="btn btn-default" data-dismiss="modal" value="انصراف" />
			</div>
		</div>
	</div>
}

@section Scripts{
	<script>
		function displayErrorMessage(error) {
			$("#errorContent").html(error);
		}

		function SubmitForm(form) {
			$.ajax({
				type: "POST",
				url: form.action,
				data: $(form).serialize(),
				success: function (data) {
					if (data.success) {
						$('body').removeClass('modal-open');
						$('.modal-backdrop').remove();
						$('#apModal').hide();

						getData('BuffetList', 'Buffet');
					} else {
						displayErrorMessage(data.message);
						return false;
					}
				}
			});
			return false;
		}
	</script>
}